### ISSUE TITLE
Adding 2nd mower configuration fails, no attributes being reported

### ISSUE THREAD

**Issue by twinkie0101** [mikey0000/Mammotion-HA#115]
### The problem

Added my second mower (both Luba 2). The first mower is added successfully and all data appears to be reporting accurately. When added the 2nd mower, config fails. Tried reloading but no success. Including logs from HAOS. 

`Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 1:29:34 PM (1 occurrences)
Last logged: 1:29:34 PM

Error setting up entry Luba-XXXXXXXX for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 90, in async_setup
    self.manager = await create_devices(ble_device, credentials, preference)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 203, in create_devices
    cloud_client = await Mammotion.login(cloud_credentials.account_id or cloud_credentials.email,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 269, in login
    await loop.run_in_executor(None, cloud_client.get_region, country_code, mammotion_http.login_info.authorization_code)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 164, in get_region
    response = client.do_request("/living/account/region/get", "https", "POST", None, body, RuntimeOptions())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alibabacloud_iot_api_gateway/client.py", line 132, in do_request
    raise UnretryableException(_last_request, _last_exception)
Tea.exceptions.UnretryableException: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

Also got this error message:
`Logger: pymammotion.aliyun.cloud_gateway
Source: /usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py:603
First occurred: 1:25:15 PM (65 occurrences)
Last logged: 1:29:37 PM

Error in sending cloud command: 29003 - None`

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.18

### What version of Home Assistant Core are you running?

 core-2024.9.1

**Comment by mikey0000** [comment]
Yeah adding a second one doesn't work right now but it's coming soon.

**Comment by twinkie0101** [comment]
Thanks. Great work so far and will close this ticket. May want to add that to the main page for reference until implemented.
