### ISSUE TITLE
periodic error in logs

### ISSUE THREAD

**Issue by leonardpitzu** [mikey0000/Mammotion-HA#116]
### The problem

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 262, in _async_update_data
    await self.async_send_command("get_report_cfg")
  File "/config/custom_components/mammotion/coordinator.py", line 208, in async_send_command
    await self.manager.send_command_with_args(
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 300, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 559, in command
    return await self.queue_command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1061, in queue_command
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1069, in _process_queue
    result = await self._execute_command_locked(key, command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1143, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 556, in send_cloud_command
    self.check_or_refresh_session()
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 494, in check_or_refresh_session
    raise Exception("Error check or refresh token: " + response_body_dict.get('msg', ''))
Exception: Error check or refresh token: 

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.21

### What version of Home Assistant Core are you running?

2024.9.1

**Comment by mikey0000** [comment]
Something went wrong trying to refresh your cloud token, unfortunately without seeing the http response I'll have to leave this till another version and add some more logs.
