### ISSUE TITLE
No Response of Luba

### ISSUE THREAD

**Issue by Striker2102** [mikey0000/Mammotion-HA#148]
### The problem

Hello,

After a few hours, the integration no longer receives status updates, and I see the following errors in the HA log.

2024-09-23 20:17:46.028 ERROR (SyncWorker_33) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:18:54.773 ERROR (SyncWorker_53) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:20:00.783 ERROR (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:21:06.947 ERROR (SyncWorker_57) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:22:13.826 ERROR (SyncWorker_40) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:23:20.776 ERROR (SyncWorker_31) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:24:26.074 ERROR (SyncWorker_55) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:25:31.932 ERROR (SyncWorker_50) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:26:38.274 ERROR (SyncWorker_38) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:27:44.893 ERROR (SyncWorker_52) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:28:51.875 ERROR (SyncWorker_13) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:29:56.967 ERROR (SyncWorker_35) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:31:04.022 ERROR (SyncWorker_19) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:32:09.968 ERROR (SyncWorker_15) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:33:15.020 ERROR (SyncWorker_38) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:34:20.775 ERROR (SyncWorker_9) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:35:10.289 ERROR (SyncWorker_5) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:35:15.763 ERROR (SyncWorker_11) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:35:20.204 ERROR (SyncWorker_20) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:35:26.688 ERROR (SyncWorker_26) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-09-23 20:36:32.039 ERROR (SyncWorker_58) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None

after reload
2024-09-23 20:46:12.472 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Luba-AMWXXXX for mammotion
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
await mammotion_coordinator.async_setup()
File "/config/custom_components/mammotion/coordinator.py", line 131, in async_setup
await device.cloud().start_sync(0)
File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/base.py", line 203, in start_sync
await self.queue_command("get_device_base_info")
File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 227, in queue_command
return await future
^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 78, in process_queue
result = await self._execute_command_locked(iot_id, key, command)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 94, in _execute_command_locked
await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, iot_id, command)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 692, in send_cloud_command
raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003

after HA restart works again for few hours

thank you :-)

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.1.45

### What version of Home Assistant Core are you running?

2024.9.1

**Comment by mikey0000** [comment]
By any chance do you have two mowers?

**Comment by Striker2102** [comment]
no i have only one Luba1

**Comment by mikey0000** [comment]
should be resolved in 0.1.55

**Comment by mikey0000** [comment]
Resolved and being tracked in the other issue #152 I'll have a new release out soon.
