### ISSUE TITLE
Integration will not load if robot is offline (not in charging station and not mowing)

### ISSUE THREAD

**Issue by rasssta** [mikey0000/Mammotion-HA#171]
### The problem

Running HASS 2024.9.3. My robot has had some issues getting back to the charging station lately and if I restart HASS in the case where the robot is stuck somewhere and can't be reached via the mobile app (via wifi) the integration will not load. I would prefer that the integration would actually load and retry connectivity to the cloud so it recovers automatically whenever the robot has been put into the charging station again.

Logs:
2024-10-03 12:39:25.544 ERROR (SyncWorker_7) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 6205 - None
2024-10-03 12:39:25.578 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Yuka-secretnum for mammotion
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/mammotion/__init__.py", line 61, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/home/homeassistant/.homeassistant/custom_components/mammotion/coordinator.py", line 283, in async_setup
    await device.cloud().start_sync(0)
  File "/srv/homeassistant/lib/python3.12/site-packages/pymammotion/mammotion/devices/base.py", line 204, in start_sync
    await self.queue_command("get_device_base_info")
  File "/srv/homeassistant/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 231, in queue_command
    return await future
           ^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 80, in process_queue
    result = await self._execute_command_locked(iot_id, key, command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 96, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, iot_id, command)
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 694, in send_cloud_command
    raise DeviceOfflineException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.DeviceOfflineException: 6205

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

0.1.59

### What version of Home Assistant Core are you running?

2024.9.3

**Comment by mikey0000** [comment]
So if I get this right there are two things here.

1. you've reloaded the integration while the robot is offline and it fails? I'll look into seeing about being able to add devices even while offline.

2. when coming back online the integration does not re-connect (I actually want to get this working I believe there is an online notification which gets sent which i need to see/ replicate to implement this)

**Comment by rasssta** [comment]
1. Correct
2. Not sure, but I don't think so. Will verify it the next time I have the chance.

**Comment by rasssta** [comment]
The integration (which hadn’t been able to load) didn’t recover now when the robot became online again. Waited 2 hours before reloading the integration manually, which worked. 

Not sure how it will handle recovery if the integration is still loaded when the robot becomes offline and then online again.

**Comment by mikey0000** [comment]
Yeah I've been a bit more conservative in trying not to hammer the servers while nailing down bugs. I'll get this sorted when I'm back.

**Comment by leonardpitzu** [comment]
Just to "second" this - my mower is offline for a good reason - it's hibernated as "winter is coming". I guess "offline" becomes a bit vague in this context.
