### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by jasonmadigan** [mikey0000/Mammotion-HA#175]
### The problem

Integration stopped working a day or two ago after an update. Deleting the integration and re-adding, I get a `Unknown error occurred` error in config flow, and this in the logs:

```
File "/config/custom_components/mammotion/config_flow.py", line 189, in async_step_wifi
File "/config/custom_components/mammotion/config_flow.py", line 271, in async_step_wifi_confirm
self._cloud_client = await Mammotion().login(account, password)
File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 241, in login
File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 153, in get_region
```

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

latest

### What version of Home Assistant Core are you running?

core-2024.10.2

**Comment by mikey0000** [comment]
Thanks for the bug report. I'm currently overseas for a bit but will take a look when I'm back.

**Comment by mikey0000** [comment]
On that, please do retry to add it, it's likely a timeout or something like that.

**Comment by jasonmadigan** [comment]
Have tried to re-add a few times now, same error. No rush, shout if I can provide any more logs. I’ll get some debug level ones.

**Comment by jasonmadigan** [comment]
Still seeing `Unknown error occurred` in config flow (WiFi setup) with `1.77`

More logs:

```
Traceback (most recent call last):
File "<string>", line 11, in __mashumaro_from_dict__
File "<string>", line 5, in __unpack_literal_LoginResponseData_token_type__983a9341f0214e06b0a42e80489c0a42
ValueError: Bearer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/mammotion/config_flow.py", line 183, in async_step_wifi
response = await connect_http(account, password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymammotion/http/http.py", line 85, in connect_http
return MammotionHTTP(login_response)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymammotion/http/http.py", line 19, in __init__
self.login_info = LoginResponseData.from_dict(response.data) if response.data else None
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<string>", line 13, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "token_type" of type Literal['bearer'] in LoginResponseData has invalid value 'Bearer'
```

**Comment by jasonmadigan** [comment]
Looks like it's related to https://github.com/mikey0000/Mammotion-HA/issues/189 - can move discussion there?

**Comment by mikey0000** [comment]
Yes same issue, closing this as its a duplicate.
