### ISSUE TITLE
protobuf: Field "categoryKey" of type Literal['LawnMower'] in DeviceProtobufMsgEventParams has invalid value 'Tracker'

### ISSUE THREAD

**Issue by tathamoddie** [mikey0000/Mammotion-HA#180]
### The problem

```
2024-10-15 10:59:57.907 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "<string>", line 19, in __mashumaro_from_dict__
  File "<string>", line 5, in __unpack_literal_DeviceProtobufMsgEventParams_categoryKey__89e1ae343304412a8c304db2c8103ab9
ValueError: Tracker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 116, in _on_mqtt_message
    await self._handle_mqtt_message(topic, payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 137, in _handle_mqtt_message
    await self._parse_mqtt_response(topic=topic, payload=payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 122, in _parse_mqtt_response
    event = ThingEventMessage.from_dicts(payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/data/mqtt/event.py", line 166, in from_dicts
    params_obj = DeviceProtobufMsgEventParams.from_dict(params_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 21, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "categoryKey" of type Literal['LawnMower'] in DeviceProtobufMsgEventParams has invalid value 'Tracker'
2024-10-15 10:59:57.949 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "<string>", line 19, in __mashumaro_from_dict__
  File "<string>", line 5, in __unpack_literal_DeviceProtobufMsgEventParams_categoryKey__89e1ae343304412a8c304db2c8103ab9
ValueError: Tracker

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 116, in _on_mqtt_message
    await self._handle_mqtt_message(topic, payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 137, in _handle_mqtt_message
    await self._parse_mqtt_response(topic=topic, payload=payload)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 122, in _parse_mqtt_response
    event = ThingEventMessage.from_dicts(payload)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/data/mqtt/event.py", line 166, in from_dicts
    params_obj = DeviceProtobufMsgEventParams.from_dict(params_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 21, in __mashumaro_from_dict__
```

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

v0.1.69

### What version of Home Assistant Core are you running?

core-2024.10.2

**Comment by mikey0000** [comment]
Don't suppose you could capture the data that was sent because I bet there is more than just Tracker that is different.

**Comment by mikey0000** [comment]
bump

**Comment by tathamoddie** [comment]
I haven't seen this again lately. Will close this for now, and re-open if I see it again but with captured data.
