### ISSUE TITLE
Offline devices not handled

### ISSUE THREAD

**Issue by CTRDevelopments** [mikey0000/Mammotion-HA#181]
### The problem

Since the last update I am getting a login error

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 11:18:29 (1 occurrences)
Last logged: 11:18:29

Error setting up entry R2 for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 61, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 296, in async_setup
    await device.cloud().start_sync(0)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/base.py", line 204, in start_sync
    await self.queue_command("get_device_base_info")
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 235, in queue_command
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 80, in process_queue
    result = await self._execute_command_locked(iot_id, key, command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion_cloud.py", line 96, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 694, in send_cloud_command
    raise DeviceOfflineException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.DeviceOfflineException: 6205

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.69

### What version of Home Assistant Core are you running?

2024.10.2

**Comment by tathamoddie** [comment]
This looks like your mower is currently offline.

`pymammotion.aliyun.cloud_gateway.DeviceOfflineException: 6205`

The integration can currently only start if the mower is online.

Turn the mower on, ensure that app connectivity works, then restart Home Assistant.

**Comment by mikey0000** [comment]
Yeah sorry! I will change this in the hopefully near future!

**Comment by CTRDevelopments** [comment]
ahh, ok, I will give that a go. Cheers

**Comment by CTRDevelopments** [comment]
sorted, many thanks

**Comment by rasssta** [comment]
Related to https://github.com/mikey0000/Mammotion-HA/issues/171. Might even wanna close this and keep all info in https://github.com/mikey0000/Mammotion-HA/issues/171?

**Comment by mikey0000** [comment]
Yes will get there 😊

**Comment by mikey0000** [comment]
The reworking Ive been doing now handles this significantly better, so I'm going to close this as its not far from being released
