### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by Strega-Technologies** [mikey0000/Mammotion-HA#47]
### The problem

Almost there, I guess, but the setup failed.
Below are the logs:
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 15:34:48 (2 occurrences)
Last logged: 15:35:49
Error setting up entry Luba-VF474GPV for mammotion

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 578, in bluetooth_device_connect
    await connect_future
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 46, in async_setup_entry
    await coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 60, in async_setup
    await self.device.start_sync(0)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/luba.py", line 189, in start_sync
    await self._send_command("get_device_base_info", retry)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/luba.py", line 268, in _send_command
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/luba.py", line 369, in _send_command_locked
    await self._ensure_connected()
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/luba.py", line 328, in _ensure_connected
    client: BleakClientWithServiceCache = await establish_connection(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_retry_connector/__init__.py", line 363, in establish_connection
    await client.connect(
  File "/usr/local/lib/python3.12/site-packages/habluetooth/wrappers.py", line 310, in connect
    connected = await super().connect(**kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 615, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 77, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/bleak_esphome/backend/client.py", line 297, in connect
    await self._client.bluetooth_device_connect(
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 594, in bluetooth_device_connect
    not await self._bluetooth_device_disconnect_guard_timeout(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 619, in _bluetooth_device_disconnect_guard_timeout
    await self.bluetooth_device_disconnect(address, timeout=timeout)
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 670, in bluetooth_device_disconnect
    await self._bluetooth_device_request(
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 724, in _bluetooth_device_request
    [response] = await self._get_connection().send_messages_await_response_complex(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aioesphomeapi/connection.py", line 818, in aioesphomeapi.connection.APIConnection.send_messages_await_response_complex
asyncio.exceptions.CancelledError

Thanks in advance...! and thank you for this initiative.

![MM2](https://github.com/user-attachments/assets/cef8a25f-7e99-4db1-b490-cc7ceac6ede3)
![MM1](https://github.com/user-attachments/assets/6bcfc5c4-b9fc-4723-adec-0188d64d0036)

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.0.4

### What version of Home Assistant Core are you running?

2024.7.3

**Comment by mikey0000** [comment]
Looks like part of the initial sync failed, you should be able to retry, I'll take a look and see what can be done. Thanks for the error log.

**Comment by Strega-Technologies** [comment]
Hi Mikey,
Have received the following screen, which means I am close to it, but this seems frozen (Luba is docked and charging) and does not reflect current state.
What can be wrong in my setup ? 
Assuming Bluetooth is connected and used on the App, I believe it cannot have another Bluetooth communication with the ESP32-BT-Proxy device at the same time, right ? 
When mowing and far away from BT, how does Luba provide its current info to your integration then ? Thanks for your help.
![2024-07-24_17-16-59](https://github.com/user-attachments/assets/a47d43a7-665f-41b1-810c-3586f36dd89a)

**Comment by mikey0000** [comment]
Can you try to reproduce in 0.0.12

**Comment by mikey0000** [comment]
Closing as stale.
