### ISSUE TITLE
Failed setup with message `'data'`

### ISSUE THREAD

**Issue by nijel** [mikey0000/Mammotion-HA#79]
### The problem

I wanted to test this integration, but the setup when trying to use Wi-Fi fails with message `'data'`:

![obrazek](https://github.com/user-attachments/assets/53d0843f-ead9-4394-afb7-4f733aa78206)

There is nothing in the Home Assistant logs.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.0

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by FuzzyMistborn** [comment]
Don't want to add "same" to this, but I'm also getting this now when I try to set it up.  I was getting a different error originally though before I deleted/redid the integration.  Error is below.  Not sure if it's related:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 9:51:22 AM (3 occurrences)
Last logged: 11:28:14 AM

Error setting up entry Luba-VF3H6B69 for mammotion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/__init__.py", line 59, in async_setup_entry
    await mammotion_coordinator.async_setup()
  File "/config/custom_components/mammotion/coordinator.py", line 89, in async_setup
    self.manager = await create_devices(ble_device, credentials, preference)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 204, in create_devices
    cloud_client = await Mammotion.login(cloud_credentials.account_id or cloud_credentials.email,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 272, in login
    await cloud_client.login_by_oauth(country_code, mammotion_http.login_info.authorization_code)
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 373, in login_by_oauth
    self._login_by_oauth_response = LoginByOAuthResponse.from_dict(data)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __mashumaro_from_dict__
mashumaro.exceptions.MissingField: Field "data" of type InnerData is missing in LoginByOAuthResponse instance
```

**Comment by mikey0000** [comment]
> data

How are you logging in? account id or email?

**Comment by FuzzyMistborn** [comment]
Email. I can try ID

**Comment by mikey0000** [comment]
@FuzzyMistborn if you have visual studio editor add on you could try bumping the pymammotion to 0.2.18 has your fix

**Comment by FuzzyMistborn** [comment]
Success!!

**Comment by mikey0000** [comment]
Awesome!

**Comment by MiddleSiggy** [comment]
I also received that message, but it was because I was using the wrong password for the account I was trying to use. 

So it is possible the login failed message needs some tweaking.

**Comment by mikey0000** [comment]
errors show up now when signing in.
