### ISSUE TITLE
No status values available

### ISSUE THREAD

**Issue by ThorstenBoettler** [mikey0000/Mammotion-HA#81]
### The problem

After update to Version v0.1.0 there are no values available. 
I connected via Wifi with credentials of my account and get no error. but All values stay "red"

<img width="1169" alt="image" src="https://github.com/user-attachments/assets/0a6a1dd0-8425-4cfc-9f2a-0a86bdb9bee9">

`2024-08-27 21:19:15.458 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: Sending command: get_report_cfg
2024-08-27 21:19:15.775 DEBUG (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 21:19:15.775 DEBUG (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 19:19:15 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '128', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'access-control-allow-headers': 'X-Requested-With,X-Sequence,X-Ca-Key,X-Ca-Secret,X-Ca-Version,X-Ca-Timestamp,X-Ca-Nonce,X-Ca-API-Key,X-Ca-Stage,X-Ca-Client-DeviceId,X-Ca-Client-AppId,X-Ca-Signature,X-Ca-Signature-Headers,X-Ca-Signature-Method,X-Forwarded-For,X-Ca-Date,X-Ca-Request-Mode,Authorization,Content-Type,Accept,Accept-Ranges,Cache-Control,Range,Content-MD5', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': 'F5C314E0-15A8-4D56-B852-116CD889D480', 'eagleeye-traceid': '0bc23a1917247863557441926e106c', 'eagleeye-traceid-daily': '0bc23a1917247863557441926e106c', 'access-control-allow-origin': '*', 'x-application-context': 'iotx-api-gateway:frankfurt:7001', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH', 'access-control-max-age': '172800'}
2024-08-27 21:19:15.775 DEBUG (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 21:19:15.775 DEBUG (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] b'{"code":29003,"id":"69aa2b8b-d745-4984-8cb4-c2fa8b675d49","localizedMsg":"identityId is blank","message":"identityId is blank"}\n'
2024-08-27 21:19:15.775 ERROR (SyncWorker_14) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-08-27 21:19:16.028 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: error in _send_command_locked: 29003
2024-08-27 21:19:16.028 ERROR (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: error in sending command -  29003
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 21:19:16.029 ERROR (MainThread) [custom_components.mammotion] Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 181, in _async_update_data
    await self.async_send_command("get_report_cfg")
  File "/config/custom_components/mammotion/coordinator.py", line 150, in async_send_command
    await self.manager.send_command_with_args(
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 300, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 554, in command
    return await self._send_command_with_args(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 21:19:16.031 DEBUG (MainThread) [custom_components.mammotion] Finished fetching mammotion data in 0.575 seconds (success: False)`

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

9d7a3f8

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
Restart the integration, it didn't connect properly

**Comment by ThorstenBoettler** [comment]
does not help, restart of integration also restart of HA does not help
I use my main account for HA and my shared account on phone.

This what I get from the debug log. 

`2024-08-27 22:03:22.557 ERROR (SyncWorker_12) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-08-27 22:03:22.809 ERROR (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: error in sending command -  29003
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 22:03:22.810 ERROR (MainThread) [custom_components.mammotion] Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 181, in _async_update_data
    await self.async_send_command("get_report_cfg")
  File "/config/custom_components/mammotion/coordinator.py", line 150, in async_send_command
    await self.manager.send_command_with_args(
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 300, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 554, in command
    return await self._send_command_with_args(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 22:03:37.452 DEBUG (Thread-12 (__thread_main)) [Paho] Sending PINGREQ
2024-08-27 22:03:37.464 DEBUG (Thread-12 (__thread_main)) [Paho] Received PINGRESP
2024-08-27 22:03:55.861 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] CountryCode: DE
2024-08-27 22:03:55.861 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] AuthCode: cPLk3Mtn9zJs83b4167c3TkD
2024-08-27 22:03:58.624 DEBUG (SyncWorker_54) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 22:03:58.624 DEBUG (SyncWorker_54) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 20:03:58 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '387', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': 'C74CA459-909C-4037-9BAC-11A4B8C6B777', 'eagleeye-traceid': '0b736deb17247890371006279e6bf2', 'access-control-allow-origin': '*', 'x-application-context': 'iotx-api-gateway:vpc-sh:7001'}
2024-08-27 22:03:58.624 DEBUG (SyncWorker_54) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 22:03:58.624 DEBUG (SyncWorker_54) [pymammotion.aliyun.cloud_gateway] b'{"code":200,"data":{"shortRegionId":"4","oaApiGatewayEndpoint":"living-account.eu-central-1.aliyuncs.com","regionId":"eu-central-1","mqttEndpoint":"public.itls.eu-central-1.aliyuncs.com:1883","pushChannelEndpoint":"living-accs.eu-central-1.aliyuncs.com","regionEnglishName":"Germany","apiGatewayEndpoint":"eu-central-1.api-iot.aliyuncs.com"},"id":"0afb71ff-4799-42d2-a599-ae2f62f025e1"}\n'
2024-08-27 22:03:58.624 DEBUG (SyncWorker_54) [pymammotion.aliyun.cloud_gateway] Endpoint: public.itls.eu-central-1.aliyuncs.com:1883
2024-08-27 22:04:00.021 DEBUG (MainThread) [pymammotion.aliyun.cloud_gateway] {'data': {'traceId': '0bc5f54217247890398574174e3141', 'vid': 'V-db796588-8fac-4cc7-a35a-d6cc1130ac91', 'code': 1, 'data': {'device': {'traceId': '0bc5f54217247890398574174e3141', 'code': 1, 'data': {'deviceId': 'bd8e42d2-371a-4913-b826-07eb4acb4810'}, 'subCode': 0, 'message': 'SUCCESS', 'successful': 'true'}, 'config': {'traceId': '0bc5f54217247890398574174e3141', 'code': 27552, 'subCode': 0, 'message': 'NO_CHANGE', 'successful': 'false'}}, 'subCode': 0, 'message': 'SUCCESS', 'successful': 'true'}, 'success': 'true', 'api': '/api/sdk/connect'}
2024-08-27 22:04:00.884 DEBUG (MainThread) [pymammotion.aliyun.cloud_gateway] {'data': {'traceId': '0bc23a3c17247890403566660efa6e', 'vid': 'V-19b8bb57-926f-43b2-8c39-77d849ba16d0', 'code': 1, 'data': {'loginSuccessResult': {'reTokenExpireIn': 7776000, 'uidToken': 'null', 'openAccount': {'displayName': 'null', 'openId': '587520446556012544', 'hasPassword': 'false', 'subAccount': 'false', 'pwdVersion': 0, 'mobileConflictAccount': 'false', 'id': 4951748, 'mobileLocationCode': '86', 'avatarUrl': '', 'domainId': 14616212, 'enableDevice': 'true', 'status': 1}, 'initPwd': 'null', 'sidExpireIn': 86400, 'oauthOtherInfo': {'SidExpiredTime': 1811189040}, 'refreshToken': 'OA-ee8e6f9f5b7b421da3097855a3f55262', 'sid': 'd46c9ab45b7249cf93166a485b445e91', 'token': 'EkuCpfnicZHr1XyfPQDqfw'}, 'mobileBindRequired': 'false'}, 'subCode': 0, 'message': 'SUCCESS', 'deviceId': '602cffd7-0640-4d96-a8aa-ac079492506e', 'successful': 'true'}, 'success': 'true', 'api': '/account/api/loginbyoauth.json', 'errorMsg': ''}
2024-08-27 22:04:00.885 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] client id 64f4fbbf
2024-08-27 22:04:00.886 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] sign(), toSignStr = appKey34231230clientId64f4fbbfdeviceSn64f4fbbf0157ad720d361bc6360fe092timestamp1724789040.8859932
2024-08-27 22:04:02.114 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 22:04:02.114 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 20:04:02 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '191', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'access-control-allow-headers': 'X-Requested-With,X-Sequence,X-Ca-Key,X-Ca-Secret,X-Ca-Version,X-Ca-Timestamp,X-Ca-Nonce,X-Ca-API-Key,X-Ca-Stage,X-Ca-Client-DeviceId,X-Ca-Client-AppId,X-Ca-Signature,X-Ca-Signature-Headers,X-Ca-Signature-Method,X-Forwarded-For,X-Ca-Date,X-Ca-Request-Mode,Authorization,Content-Type,Accept,Accept-Ranges,Cache-Control,Range,Content-MD5', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': '32A1BEEC-F7F8-4B1C-89B1-F30BC3530E21', 'eagleeye-traceid': '0bc239e117247890413875806ebe82', 'eagleeye-traceid-daily': '0bc239e117247890413875806ebe82', 'access-control-allow-origin': '*', 'x-application-context': 'iotx-api-gateway:frankfurt:7001', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH', 'access-control-max-age': '172800'}
2024-08-27 22:04:02.114 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 22:04:02.114 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] b'{"code":200,"data":{"deviceSecret":"0eeb99934d8c00fdea48a92034935d78","productKey":"a5vlvzwIhhj","deviceName":"64f4fbbf0157ad720d361bc6360fe092"},"id":"62f38133-da02-41dd-b533-1e1ed4e625cf"}\n'
2024-08-27 22:04:02.114 DEBUG (SyncWorker_25) [pymammotion.aliyun.cloud_gateway] {'code': 200, 'data': {'deviceSecret': '0eeb99934d8c00fdea48a92034935d78', 'productKey': 'a5vlvzwIhhj', 'deviceName': '64f4fbbf0157ad720d361bc6360fe092'}, 'id': '62f38133-da02-41dd-b533-1e1ed4e625cf'}
2024-08-27 22:04:02.238 DEBUG (SyncWorker_18) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 22:04:02.238 DEBUG (SyncWorker_18) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 20:04:02 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '269', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'access-control-allow-headers': 'X-Requested-With,X-Sequence,X-Ca-Key,X-Ca-Secret,X-Ca-Version,X-Ca-Timestamp,X-Ca-Nonce,X-Ca-API-Key,X-Ca-Stage,X-Ca-Client-DeviceId,X-Ca-Client-AppId,X-Ca-Signature,X-Ca-Signature-Headers,X-Ca-Signature-Method,X-Forwarded-For,X-Ca-Date,X-Ca-Request-Mode,Authorization,Content-Type,Accept,Accept-Ranges,Cache-Control,Range,Content-MD5', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': 'E58AAE22-CBD0-4BCF-83FC-56CC4E6958DC', 'eagleeye-traceid': '0aba363b17247890421243203ecbc2', 'eagleeye-traceid-daily': '0aba363b17247890421243203ecbc2', 'access-control-allow-origin': '*', 'x-application-context': 'iotx-api-gateway:frankfurt:7001', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH', 'access-control-max-age': '172800'}
2024-08-27 22:04:02.238 DEBUG (SyncWorker_18) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 22:04:02.238 DEBUG (SyncWorker_18) [pymammotion.aliyun.cloud_gateway] b'{"code":200,"data":{"identityId":"5000opb45092fde631bb50ea5f615e464f5e1860","refreshTokenExpire":720000,"iotToken":"60c1895218f6a2ed2bf30faba0215dbe","iotTokenExpire":72000,"refreshToken":"1CB7D67DDC338A6DD77FE1067C65432B"},"id":"3149ccd8-1d80-43e9-aa81-5aace1124a44"}\n'
2024-08-27 22:04:02.361 DEBUG (SyncWorker_35) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 22:04:02.361 DEBUG (SyncWorker_35) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 20:04:02 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '1324', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'access-control-allow-headers': 'X-Requested-With,X-Sequence,X-Ca-Key,X-Ca-Secret,X-Ca-Version,X-Ca-Timestamp,X-Ca-Nonce,X-Ca-API-Key,X-Ca-Stage,X-Ca-Client-DeviceId,X-Ca-Client-AppId,X-Ca-Signature,X-Ca-Signature-Headers,X-Ca-Signature-Method,X-Forwarded-For,X-Ca-Date,X-Ca-Request-Mode,Authorization,Content-Type,Accept,Accept-Ranges,Cache-Control,Range,Content-MD5', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': '16F72690-6FB7-4B61-A4A1-333452B14A02', 'eagleeye-traceid-daily': '0aba343d17247890422494883e00d7', 'eagleeye-traceid': '0aba343d17247890422494883e00d7', 'access-control-allow-origin': '*', 'vary': 'Accept-Encoding, Accept-Encoding', 'x-application-context': 'iotx-api-gateway:frankfurt:7001', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH', 'access-control-max-age': '172800'}
2024-08-27 22:04:02.361 DEBUG (SyncWorker_35) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 22:04:02.361 DEBUG (SyncWorker_35) [pymammotion.aliyun.cloud_gateway] b'{"code":200,"data":{"total":2,"data":[{"productModel":"LubaVAWD5000","gmtModified":1707586389000,"netType":"NET_WIFI","nickName":"Lucy","categoryKey":"LawnMower","isEdgeGateway":false,"productKey":"a1LLmy1zc0j","nodeType":"DEVICE","deviceName":"Luba-VSFU4LWD","categoryName":"\xe5\x89\xb2\xe8\x8d\x89\xe6\x9c\xba","identityAlias":"UNKNOW","productName":"Luba2","iotId":"drSAM1mnKFKdTNTmlIu3000000","bindTime":1707586389000,"owned":1,"identityId":"5000opb45092fde631bb50ea5f615e464f5e1860","thingType":"DEVICE","status":1},{"productModel":"ReferenceStation","gmtModified":1707561809000,"categoryImage":"https://ai-genie-center.oss-cn-hangzhou.aliyuncs.com/app-data/iot-center/static_category/Tracker/\xe5\xae\x9a\xe4\xbd\x8d\xe7\xbb\x88\xe7\xab\xaf\xe5\xa4\x87\xe4\xbb\xbd.png","netType":"NET_WIFI","nickName":"RTKStation","categoryKey":"Tracker","isEdgeGateway":false,"productKey":"a1Nc68bGZzX","nodeType":"DEVICE","deviceName":"RTKBEU235036268","categoryName":"\xe5\xae\x9a\xe4\xbd\x8d\xe7\xbb\x88\xe7\xab\xaf","identityAlias":"UNKNOW","productName":"ReferenceStation","iotId":"pgaL12jRHazXnbyORURF000000","productImage":"https://ai-genie-center.oss-cn-hangzhou.aliyuncs.com/app-data/iot-center/static_category/Tracker/\xe5\xae\x9a\xe4\xbd\x8d\xe7\xbb\x88\xe7\xab\xaf\xe5\xa4\x87\xe4\xbb\xbd.png","bindTime":1707561809000,"owned":1,"identityId":"5000opb45092fde631bb50ea5f615e464f5e1860","thingType":"DEVICE","status":1}],"pageNo":1,"pageSize":100},"id":"bd66393e-048f-4f94-ad93-b7b972a02b77"}\n'
2024-08-27 22:04:37.520 DEBUG (Thread-12 (__thread_main)) [Paho] Sending PINGREQ
2024-08-27 22:04:37.534 DEBUG (Thread-12 (__thread_main)) [Paho] Received PINGRESP
2024-08-27 22:05:02.387 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: Sending command: get_report_cfg
2024-08-27 22:05:02.847 DEBUG (SyncWorker_16) [pymammotion.aliyun.cloud_gateway] OK
2024-08-27 22:05:02.847 DEBUG (SyncWorker_16) [pymammotion.aliyun.cloud_gateway] {'date': 'Tue, 27 Aug 2024 20:05:02 GMT', 'content-type': 'application/json;charset=UTF-8', 'content-length': '128', 'connection': 'keep-alive', 'keep-alive': 'timeout=25', 'access-control-allow-headers': 'X-Requested-With,X-Sequence,X-Ca-Key,X-Ca-Secret,X-Ca-Version,X-Ca-Timestamp,X-Ca-Nonce,X-Ca-API-Key,X-Ca-Stage,X-Ca-Client-DeviceId,X-Ca-Client-AppId,X-Ca-Signature,X-Ca-Signature-Headers,X-Ca-Signature-Method,X-Forwarded-For,X-Ca-Date,X-Ca-Request-Mode,Authorization,Content-Type,Accept,Accept-Ranges,Cache-Control,Range,Content-MD5', 'server': 'Tengine', 'timing-allow-origin': '*', 'x-ca-request-id': 'FD77199C-625B-45F2-A6EA-02DE8B1983F3', 'eagleeye-traceid': '0aba343917247891028083218e710f', 'eagleeye-traceid-daily': '0aba343917247891028083218e710f', 'access-control-allow-origin': '*', 'x-application-context': 'iotx-api-gateway:frankfurt:7001', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH', 'access-control-max-age': '172800'}
2024-08-27 22:05:02.847 DEBUG (SyncWorker_16) [pymammotion.aliyun.cloud_gateway] 200
2024-08-27 22:05:02.847 DEBUG (SyncWorker_16) [pymammotion.aliyun.cloud_gateway] b'{"code":29003,"id":"6f4d7bc3-117f-43b6-8d69-48d6a3aeef7c","localizedMsg":"identityId is blank","message":"identityId is blank"}\n'
2024-08-27 22:05:02.847 ERROR (SyncWorker_16) [pymammotion.aliyun.cloud_gateway] Error in sending cloud command: 29003 - None
2024-08-27 22:05:03.099 DEBUG (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: error in _send_command_locked: 29003
2024-08-27 22:05:03.099 ERROR (MainThread) [pymammotion.mammotion.devices.mammotion] Lucy: error in sending command -  29003
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 22:05:03.099 ERROR (MainThread) [custom_components.mammotion] Unexpected error fetching mammotion data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mammotion/coordinator.py", line 181, in _async_update_data
    await self.async_send_command("get_report_cfg")
  File "/config/custom_components/mammotion/coordinator.py", line 150, in async_send_command
    await self.manager.send_command_with_args(
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 300, in send_command_with_args
    return await device.cloud().command(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 554, in command
    return await self._send_command_with_args(key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _send_command_with_args
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1072, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1088, in _execute_command_locked
    await self.loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 592, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003
2024-08-27 22:05:03.103 DEBUG (MainThread) [custom_components.mammotion] Finished fetching mammotion data in 0.718 seconds (success: False)`

**Comment by ThorstenBoettler** [comment]
with v0.1.1 it seams to work. I had directly values
