### ISSUE TITLE
Mammotion Yuka via WiFi - Issues with the current state or changing of configuration entities (Switches, Numbers, ..)

### ISSUE THREAD

**Issue by Tra1n84** [mikey0000/Mammotion-HA#90]
### The problem

Hello,

I'm using my Yuka mower via the newly added WiFi support and an additional created Mammotion account, which i shared my mower with. Login is done via e-mail address and password and not via the account number.

The mower was sucessfully found and entity sensors (such as Battery level, Blade height, Progress etc.) working fine so far but the configuration entities like the buttons, switches and numbers are not showing the current state and when i try to change some of these entities (like Rain detection on/off) it is giving me the error message: "object NoneType can't be used in 'await' expression".

I wasn't really sure if this problem is related to another created issue already or if this has already been discussed, but i couldn't find it in other issues. Therefor i create a new issue here.

I've collected the error logs shown in the Home Assistant core protocol:

**After Mower was added to the devices:**

`Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:148

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1011, in run_periodic_sync_task
    await self._ble_sync()
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1005, in _ble_sync
    await loop.run_in_executor(None, self._mqtt_client.get_cloud_client().send_cloud_command, self.iot_id, command_bytes)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/aliyun/cloud_gateway.py", line 609, in send_cloud_command
    raise SetupException(response_body_dict.get("code"))
pymammotion.aliyun.cloud_gateway.SetupException: 29003`

`Logger: pymammotion.mammotion.devices.mammotion
Source: /usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py:1069

Yuka: error in sending command -
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mqtt/mammotion_future.py", line 23, in async_get
    return await self.fut
           ^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1067, in _send_command
    return await self._send_command_locked(key, command_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1075, in _send_command_locked
    return await self._execute_command_locked(key, command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1111, in _execute_command_locked
    notify_msg = await future.async_get(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mqtt/mammotion_future.py", line 22, in async_get
    async with async_timeout.timeout(timeout):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError`

**After trying to change some of the configuration entities:**

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:241

[546621436640] Unexpected exception
[546300885840] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mammotion/switch.py", line 98, in async_turn_off
    await self.entity_description.set_fn(self.coordinator, False)
TypeError: object NoneType can't be used in 'await' expression`

Maybe this helps to find out where the issue comes from. If you need more information or logs, do not hesitate to ask for it. I really like that someone is working that hard on a Home Assistant integration for Mammotion and i am willing to help whereever i can.

Thanks a lot & Best regards
Thomas

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

v0.1.3

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
Hey thanks, integration is under heavy development, some features do not work yet or are in progress, including those. Join on discord if you'd like to keep up with progress.
