### ISSUE TITLE
"User not exist"

### ISSUE THREAD

**Issue by nappyjim** [mikey0000/Mammotion-HA#97]
### The problem

When I load integration, it asks for email and password.  I put in email and password that I use to log on to Mammotion app on my phone, and it returns "user not exist".  I also tried using my account number as its displayed in the Mammotion app, but I get same error.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.11

### What version of Home Assistant Core are you running?

core-2024.8.3

**Comment by mikey0000** [comment]
Using with or without Bluetooth?

**Comment by nappyjim** [comment]
> Using with or without Bluetooth?

I am assuming with, but I cant say for sure. As I dont have any options to select first. The integration goes straight to asking me for a login.

**Comment by mikey0000** [comment]
OK that's without, using a standard account? E.g not Google or something else? I'll have a release out today, which may or may not solve your problem. Otherwise make sure you've got no typos as that response comes back from the mammotion server

**Comment by nappyjim** [comment]
> OK that's without, using a standard account? E.g not Google or something else? I'll have a release out today, which may or may not solve your problem. Otherwise make sure you've got no typos as that response comes back from the mammotion server

I also tried my google login (which also works for the Mammotion app), but that didnt work either.  I reset my mammotion password, and still same error.

**Comment by mikey0000** [comment]
Can you update to 0.1.12 and see if it's any better?

**Comment by mikey0000** [comment]
Odd, could you jump on discord and pm me?

**Comment by tlm4594** [comment]
Okay I got mine to work on 0.1.11 last night... This morning it showed errors and couldn't connect. I noticed this thread, updated to 0.11.12 and it now connects but says unavailable. So my main Mammotion account is connected through google unfortunately, but I created a shared account for my wife with email and that worked with this integration last night! I was pumped. Updating to the latest at least now shows success when loading the integration, but it still shows my Yuka unavailable. Here's the error:

Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:148
First occurred: 9:53:15 AM (2 occurrences)
Last logged: 9:54:21 AM

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1019, in on_ready
    self.loop.create_task(self.on_ready_callback)
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 458, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got <function MammotionDataUpdateCoordinator.async_setup.<locals>.<lambda> at 0x7f67e104ae80>

**Comment by tlm4594** [comment]
> Okay I got mine to work on 0.1.11 last night... This morning it showed errors and couldn't connect. I noticed this thread, updated to 0.11.12 and it now connects but says unavailable. So my main Mammotion account is connected through google unfortunately, but I created a shared account for my wife with email and that worked with this integration last night! I was pumped. Updating to the latest at least now shows success when loading the integration, but it still shows my Yuka unavailable. Here's the error:
> 
> Logger: homeassistant Source: /usr/src/homeassistant/homeassistant/runner.py:148 First occurred: 9:53:15 AM (2 occurrences) Last logged: 9:54:21 AM
> 
> Error doing job: Future exception was never retrieved (None) Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pymammotion/mammotion/devices/mammotion.py", line 1019, in on_ready self.loop.create_task(self.on_ready_callback) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 458, in create_task task = tasks.Task(coro, loop=self, name=name, context=context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: a coroutine was expected, got <function MammotionDataUpdateCoordinator.async_setup.. at 0x7f67e104ae80>

Okay now it just connected again. I'll keep ya posted.

**Comment by mikey0000** [comment]
please update to 0.1.15
